application: steam-matchup
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: latest

handlers: 
- url: /api/.*
  script: steam_matchup.api.application

- url: /auth/
  script: steam_matchup.auth.application

- url: /styles
  static_dir: static/styles/

- url: /scripts/models
  static_dir: static/scripts/models

- url: /scripts
  static_dir: static/scripts/

- url: /
  upload: static/index\.html
  static_files: static/index.html
